backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "news"
    label: "News"
    folder: "src/pages/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "news-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "research"
    label: "Research Topics"
    folder: "src/pages/research"
    create: true
    slug: "{{slug}}"
    filter: {field: "templateKey", value: "research-post"}
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "research-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Photo", name: "photo", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "components"
    label: "Components"
    files:
      - file: "src/pages/carousel/index.md"
        label: "Carousel"
        name: "carousel"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Carousel Slides", name: "carouselSlides", widget: "list", fields: [{label: Description, name: description, widget: string},{label: Photo, name: photo, widget: image}]}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/publications/index.md"
        label: "Publications"
        name: "publications"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "publications-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/team/index.md"
        label: "Team"
        name: "team"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "team-page"}
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Members, name: members, widget: list, fields: [{label: Name, name: name, widget: string}, {label: Position, name: position, widget: string}, {label: Photo, name: photo, widget: image}, {label: Description, name: description, widget: text}]}
          - file: "src/pages/team/index.md"
        label: "Alumni"
        name: "alumni"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "alumni-page"}
          - {label: Title, name: title, widget: string}
          - {label: Heading, name: heading, widget: string}
          - {label: Members, name: members, widget: list, fields: [{label: Name, name: name, widget: string}, {label: Position, name: position, widget: string}, {label: Photo, name: photo, widget: image}, {label: Description, name: description, widget: text}]}